/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n=function(c){var d=0;return function(){return d<c.length?{done:!1,value:c[d++]}:{done:!0}}},u=function(c){var d="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return d?d.call(c):{next:n(c)}},v=function(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<c.length;++d){var h=c[d];if(h&&h.Math==Math)return h}throw Error("Cannot find global object");},w=v(this),x="function"==typeof Object.defineProperties?
Object.defineProperty:function(c,d,h){if(c==Array.prototype||c==Object.prototype)return c;c[d]=h.value;return c},z=function(c,d){if(d)a:{var h=w;c=c.split(".");for(var k=0;k<c.length-1;k++){var f=c[k];if(!(f in h))break a;h=h[f]}c=c[c.length-1];k=h[c];d=d(k);d!=k&&null!=d&&x(h,c,{configurable:!0,writable:!0,value:d})}};
z("Promise",function(c){function d(){this.a=null}function h(a){return a instanceof f?a:new f(function(b){b(a)})}if(c)return c;d.prototype.b=function(a){if(null==this.a){this.a=[];var b=this;this.c(function(){b.g()})}this.a.push(a)};var k=w.setTimeout;d.prototype.c=function(a){k(a,0)};d.prototype.g=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;++b){var e=a[b];a[b]=null;try{e()}catch(g){this.f(g)}}}this.a=null};d.prototype.f=function(a){this.c(function(){throw a;
})};var f=function(a){this.b=0;this.c=void 0;this.a=[];this.j=!1;var b=this.f();try{a(b.resolve,b.reject)}catch(e){b.reject(e)}};f.prototype.f=function(){function a(g){return function(l){e||(e=!0,g.call(b,l))}}var b=this,e=!1;return{resolve:a(this.v),reject:a(this.g)}};f.prototype.v=function(a){if(a===this)this.g(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof f)this.B(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?
this.u(a):this.i(a)}};f.prototype.u=function(a){var b=void 0;try{b=a.then}catch(e){this.g(e);return}"function"==typeof b?this.m(b,a):this.i(a)};f.prototype.g=function(a){this.l(2,a)};f.prototype.i=function(a){this.l(1,a)};f.prototype.l=function(a,b){if(0!=this.b)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.b);this.b=a;this.c=b;2===this.b&&this.A();this.o()};f.prototype.A=function(){var a=this;k(function(){if(a.s()){var b=w.console;"undefined"!==typeof b&&b.error(a.c)}},
1)};f.prototype.s=function(){if(this.j)return!1;var a=w.CustomEvent,b=w.Event,e=w.dispatchEvent;if("undefined"===typeof e)return!0;"function"===typeof a?a=new a("unhandledrejection",{cancelable:!0}):"function"===typeof b?a=new b("unhandledrejection",{cancelable:!0}):(a=w.document.createEvent("CustomEvent"),a.initCustomEvent("unhandledrejection",!1,!0,a));a.promise=this;a.reason=this.c;return e(a)};f.prototype.o=function(){if(null!=this.a){for(var a=0;a<this.a.length;++a)y.b(this.a[a]);this.a=null}};
var y=new d;f.prototype.B=function(a){var b=this.f();a.h(b.resolve,b.reject)};f.prototype.m=function(a,b){var e=this.f();try{a.call(b,e.resolve,e.reject)}catch(g){e.reject(g)}};f.prototype.then=function(a,b){function e(m,p){return"function"==typeof m?function(q){try{g(m(q))}catch(r){l(r)}}:p}var g,l,t=new f(function(m,p){g=m;l=p});this.h(e(a,g),e(b,l));return t};f.prototype.catch=function(a){return this.then(void 0,a)};f.prototype.h=function(a,b){function e(){switch(g.b){case 1:a(g.c);break;case 2:b(g.c);
break;default:throw Error("Unexpected state: "+g.b);}}var g=this;null==this.a?y.b(e):this.a.push(e);this.j=!0};f.resolve=h;f.reject=function(a){return new f(function(b,e){e(a)})};f.race=function(a){return new f(function(b,e){for(var g=u(a),l=g.next();!l.done;l=g.next())h(l.value).h(b,e)})};f.all=function(a){var b=u(a),e=b.next();return e.done?h([]):new f(function(g,l){function t(q){return function(r){m[q]=r;p--;0==p&&g(m)}}var m=[],p=0;do m.push(void 0),p++,h(e.value).h(t(m.length-1),l),e=b.next();
while(!e.done)})};return f});var A=this||self,B=/^[\w+/_-]+[=]{0,2}$/,C=null,D=function(){var c=A.document;return(c=c.querySelector&&c.querySelector("script[nonce]"))&&(c=c.nonce||c.getAttribute("nonce"))&&B.test(c)?c:""};function E(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");F()}var F,G=null;
function H(){if(G)return G;window.performance.mark("gapi_load_start");var c=window.colabExperiments&&window.colabExperiments.first_party_auth;return G=new Promise(function(d,h){F=d;window.gapi_onload=function(){c?F():gapi.load("auth:client",E)};var k=document.createElement("script");k.src="https://apis.google.com/js/client.js";k.async=!0;null===C&&(C=D());(d=C)&&k.setAttribute("nonce",d);k.onerror=function(){h(Error("Error loading "+k.src))};d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(k,
d)})}window.colab_gapi_loader={};window.colab_gapi_loader.load=H;H().then(function(){},function(){});
